### ISSUE TITLE
UI 'stop' button does not stop test

### ISSUE THREAD

**Issue by colmsnowplow** [locustio/locust#1047]
### Description of issue

Using the web UI, the 'Stop' button temporarily slows down requests sent, which then rise back to previous levels.

Stop button then disappears.

Running on AWS EC2, 3 slaves.

### Expected behavior

Stop button is expected to stop sending requests completely.

### Actual behavior

RPS temporarily drops then resumes back to its previous level

### Steps to reproduce (for bug reports)

- Configure locust on EC2 with 3 slaves, simple GET request test scenario (4 different requests)
- Config of 100 users, 1 swarm rate (via web UI)
- Attempt to stop test using 'stop' button.

**Comment by ernestom** [comment]
I see this behavior constantly as well with any number of slaves.

**Comment by georgevreilly-stripe** [comment]
This is https://github.com/locustio/locust/issues/981, which was fixed in https://github.com/locustio/locust/pull/982. However, this fix has never been released.

@cgoldberg, I reverted to 0.9.0 because this behavior is causing me severe problems. Please make a new release.

Also, although 0.11.0 is available at [PyPI](https://pypi.org/project/locustio/#history), it's never been tagged in this repo as a release.

**Comment by tsykora-verimatrix** [comment]
I've the same problem with 0.11.0.
We hit one of our endpoints hard (30+ slaves) and after hitting stop button in the UI the tests went on causing problems to one of our services. We had to physically take down those slaves to stop the test.

**Comment by georgevreilly-stripe** [comment]
I'm running 16 slaves† and the tests just won't stop until I kill the master process. There's a separate watchdog process that monitors the target's health and it is unable to stop the tests when running under Locust 0.11.

† This "slave" terminology is really unfortunate. "Worker" would be descriptive and inoffensive.

**Comment by max-rocket-internet** [comment]
We have the same problem. Running on k8s we have to delete all master and slave pods to reliably stop the test. It's quite annoying 😅

**Comment by rafaelbco** [comment]
> Also, although 0.11.0 is available at [PyPI](https://pypi.org/project/locustio/#history), it's never been tagged in this repo as a release.

I'm quite confused about this too. Also, there are not Changelog entries for 0.11.0

**Comment by cyberw** [comment]
Hi all! Have you tried the latest release? (0.12.1)

**Comment by heyman** [comment]
I believe this should be fixed in the latest release (fixed in #982 as mentioned by @georgevreilly-stripe )

> † This "slave" terminology is really unfortunate. "Worker" would be descriptive and inoffensive.

Check out #220. I'd be happy to merge a PR that changes that terminology.

**Comment by PanZhenhua** [comment]
Hello, I found that the problem still exists in the current latest version 2.13.0

**Comment by cyberw** [comment]
2.13 is not compatible with python 3.6 - how did you even manage to install it?

**Comment by PanZhenhua** [comment]
Sorry, I remember wrong, my locust version is 2.8.4, Python version is 3.6.8. However, this problem still exists when I tried to use the latest python and locust versions before, which is probably caused by the communication between the master node and the worker node or other problems. This problem does not exist when a single worker executes
