### ISSUE TITLE
Response Times graph broken (drops to 0 after a while)

### ISSUE THREAD

**Issue by skivis** [locustio/locust#1157]
### Describe the bug
Something has broken in regards to the reporting (specifically the Response Times graph) in the web UI in distributed mode (with docker). Whenever I start a new test run with locust `0.13.1` the graph updates just fine for the first 10-20 seconds and the drops to 0 and doesn't recover from this weird behavior... The statistics tab updates just fine and is not affected but the graph just breaks for some reason.

<img width="1440" alt="ResponseTimesGraph" src="https://user-images.githubusercontent.com/2919796/69062669-90536280-0a1b-11ea-9d6d-1b70588a96f4.png">

I haven't done much investigation at all into why this is happening since I'm at work atm but I'm putting this out there because maybe someone has an idea of what could be causing this. Lots of activity in the past week, maybe someone has an aha moment.

### Expected behavior
The graph should update as usual

### Actual behavior
Graph drops to zero, haven't checked to response from the polls but I suspect something funny is going on there

### Steps to reproduce
```
$ git clone https://github.com/locustio/locust.git
$ cd locust/examples/docker-compose
$ docker-compose up
```

Open up localhost:8089 and run 20 users ramping up 1/sec. Defect should show itself within 10-20 seconds.

### Environment settings

- OS: Mac & Windows & Docker
- Python version: 3.7
- Locust version: 0.13.1

**Comment by heyman** [comment]
I can reproduce the error and I've identified the cause. Working on a fix now!

**Comment by heyman** [comment]
I've pushed 0.13.2 to PyPI. New Docker images should be building right now.

**Comment by skivis** [comment]
Awesome! Thanks for super fast fix!

**Comment by akaicn** [comment]
I have already updated to 0.13.5, but response time graph broken still occurs.
