### ISSUE TITLE
Time response graph is not working on master/slave configuration

### ISSUE THREAD

**Issue by davidgca** [locustio/locust#1182]
After migrating to last python and locust releases and running a master-slave configuration in docker (one container for each master-slave node), the time response graph is not working: "No data" is showing by move pointer to the response-time line  (see attached images). 

![Locust error1](https://user-images.githubusercontent.com/26218314/69954255-28147e80-14fb-11ea-9bd4-a6c43a0ca3e9.png)

![error locust summary1](https://user-images.githubusercontent.com/26218314/69954264-2e0a5f80-14fb-11ea-8900-52a9fa0f13c0.png)

NOTE: Download data function is working well

### Expected behaviour
Time response graph should display all average response time distribution for the current execution

### Actual behaviour
After some seconds average response time goto "No data", Clicking on reset stats, the data return for 2-3 seconds and again drop to 0. The behaviours cannot be reproduced on a single container execution (without master/slaves):

![error locust 4](https://user-images.githubusercontent.com/26218314/69954629-08ca2100-14fc-11ea-92e9-964bb77a5e96.png)

### Steps to reproduce
Update locust and python to last releases and rerun the cluster

### Environment settings

Locust version: 0.13.1
Python/alpine version: python:3.8.0-alpine3.10
docker version:17.05.0-ce running on debian 9

**Comment by heyman** [comment]
This was fixed in 0.13.2 (https://github.com/locustio/locust/blob/master/CHANGELOG.md#0132).

**Comment by abinjaik** [comment]
We still get this issue with 0.14.x Locust... Charts goes off after sometimes

**Comment by heyman** [comment]
@abinjaik:
I don't think you're experiencing a regression of this issue, since this bug was only for the response time graph, and if I understand [you](https://github.com/locustio/locust/issues/1263#issuecomment-592695669) correctly all graphs stops working?

I'm not able to reproduce your issue. Feel free to open a new ticket with as much information as possible on how to reproduce the issue. And if possible provide us with a minimal reproducible code example.

**Comment by abinjaik** [comment]
Yes, I am having locust 0.14/latest, running on 8 core , 16 GB Linux Master
and running 6-7 slaves each on 2 of the other machines with similar
configuration. Yes, we run slaves on the same machine of Master as well -
assume that's fine. After certain load the charts tab, slaves tab and R/s
etc on the locust dashboard shows empty - no data. We tried using Chrome
and Firefox on the same machine , also tried the ip-port http url from
other machines, everywhere we have this issue

**Comment by heyman** [comment]
When this happens do you see any errors in the browser/javascript console? What happens if you reload the page? How is the CPU usage of the master?

For me to be able to help you I really need a way to reproduce the issue.

**Comment by abinjaik** [comment]
> When this happens do you see any errors in the browser/javascript console? What happens if you reload the page? How is the CPU usage of the master?
> 
> For me to be able to help you I really need a way to reproduce the issue.

I ran the tests again to see when it dies. CPU was in a good condition on master, this time i didnt had slaves on the same Master machine. One of the observation is, I got an exception on the ssh client of one of slaves, which is from our script I guess. But does the issue or exception thrown from load test scripts affects web dashboard? Also, I can see errors on browser consoles, first one seems like an issue with JS scripts file on dashboard. But others are just invalid, because it is trying to access images on our web apps using the IP of the Locust master :) - See screen shots below.

![image](https://user-images.githubusercontent.com/26336277/75719368-7f0c2a00-5c89-11ea-932e-2bca0ade2d24.png)

![image](https://user-images.githubusercontent.com/26336277/75719515-bda1e480-5c89-11ea-8ca9-605498e0b238.png)

![image](https://user-images.githubusercontent.com/26336277/75719653-f80b8180-5c89-11ea-92b7-7b86e1c171a3.png)
