### ISSUE TITLE
Locust Helm Chart update

### ISSUE THREAD

**Issue by bwcho75** [locustio/locust#1210]
Hello guys.
Thanx for developing great tools.
Locust can be leveraged by Helm over Kubernetes with easy install.
Unfortunately official helm chart for Locust is using Locust 0.9.0 image. I simply changed the image version to 0.13.5 but it didn't work. I suppose that there were some changes and the Helm chart needs to be updated followed by locust version up.
Could you please update the helm chart for recent version of locust?
Locust 0.9.0 seems to have different taskSet grammer etc

**Comment by cyberw** [comment]
Hi! Are you talking about this helm chart https://github.com/helm/charts/tree/master/stable/locust ?

I think you should file a ticket with them instead :)

**Comment by limakzi** [comment]
@cyberw @bwcho75 As of there is [no support for `charts/stable`](https://github.com/helm/charts/tree/master/stable/locust) are you planning or need support with deploying Helm Chart in `locustio` organization?

I would love to help you, make the pull-request and maintain that, if you need.

**Comment by cyberw** [comment]
I havent used helm enough to know if having the chart in our repo makes sense or not, but I dont see any problems with it. A PR would be most welcome!

**Comment by max-rocket-internet** [comment]
@limakzi do you mean just committing the chart to this repo? Or do you mean setting up ChartMuseum and hosting a real helm repo for the locust chart?

**Comment by limakzi** [comment]
@max-rocket-internet I mean committing the chart into this repository.
I do not see any good reason for managing ChartMuseum on our own, besides the state of the art.
- More work to be done.
- More difficult to maintain.

Lets build the Helm Chart, push it here or create separate repository.
- `external-secrets` [used Github pages](https://external-secrets.github.io).
- `anchore` [moved the Helm Chart into separate repository](https://github.com/anchore/anchore-charts).

Both solutions are fine. 👍🏻

**Comment by max-rocket-internet** [comment]
> I mean committing the chart into this repository or managing separate repository with Chart only

OK, makes sense.

> I do not see any good reason for managing ChartMuseum on our own, besides the state of the art.

It's a pain to use if you don't have a real chart repo as you can't do versioning of the chart and you need a local copy of this repo. But I guess it's still better than nothing.

> Lets build the Helm Chart

I already maintain a locust chart [here](https://github.com/deliveryhero/helm-charts/tree/master/stable/locust), it's already in the locust docs, you could start by just copying this chart. Up to you though 🙂

**Comment by limakzi** [comment]
@max-rocket-internet Ouch, perfect! I haven't seen it before. Awesome job!
So, what I would change the owner, to make it _kinda_ official.

I have reviewed this Chart and I would do some things a little bit different, but this is completely different discussion.

**Comment by max-rocket-internet** [comment]
> So, what I would change the owner, to make it kinda official.

Just copy it to this repo, update the `Chart.yaml` and then iterate changes in this repo I guess.

**Comment by limakzi** [comment]
@max-rocket-internet The question is, if we agree upon keeping `index.yaml` and `tar.gz` in Github repository.

**Comment by max-rocket-internet** [comment]
@limakzi 

> The question is, if we agree upon keeping index.yaml and tar.gz in Github repository.

Sorry, I don't understand this?

> please, create new repository with Chart only.

I am not a maintainer and cannot create repos under locustio org 🙂

**Comment by limakzi** [comment]
@cgbystrom, @heyman Can we have a separate repository for Helm Chart?

**Comment by heyman** [comment]
I've created a new repository at https://github.com/locustio/helm-chart. You should both have write access to it @limakzi and @max-rocket-internet 

Is **locust/helm-chart** a good name? Let me know if I should rename it to something else.

**Comment by limakzi** [comment]
@heyman  `locust-chart` looks perfect.
I will create pull request there.

**Comment by consideRatio** [comment]
So step 1 is to migrate the old Helm chart right? When that happens, it would be good to preserve the git history to some degree. Is that possible even though hashes would change etc because it would mean a rewritten history?

**Comment by max-rocket-internet** [comment]
> I've created a new repository at https://github.com/locustio/helm-chart. You should both have write access to it @limakzi and @max-rocket-internet

Nice one @heyman 

> I will create pull request there.
> So step 1 is to migrate the old Helm chart right?

For which chart though? The old one from `helm/charts/stable` was pretty simplistic I think, also using an old  random custom docker image. I think [this one](https://github.com/deliveryhero/helm-charts/tree/master/stable/locust) is better?

**Comment by heyman** [comment]
> For which chart though? The old one from helm/charts/stable was pretty simplistic I think, also using an old random custom docker image. I think this one is better?

The old one was never an official one, and if the one you linked is better, I think we should use that one as the starting point (or maybe it's even fine to use as is?). My own experience with helm charts is very limited.

**Comment by max-rocket-internet** [comment]
OK here's an initial PR for the chart: https://github.com/locustio/helm-chart/pull/1

**Comment by cyberw** [comment]
This is fixed.

**Comment by max-rocket-internet** [comment]
It kind of isn't fixed though, it's still waiting on @sekka1 to setup the chart artifacts/DNS part in https://github.com/locustio/helm-chart/issues/2

**Comment by cyberw** [comment]
Aha, I misunderstood...

**Comment by cyberw** [comment]
bad bot

**Comment by sekka1** [comment]
@max-rocket-internet this kind dropped off my radar.  What are you still waiting on me for?

**Comment by max-rocket-internet** [comment]
@sekka1 same as here: https://github.com/locustio/locust/issues/1210#issuecomment-820218507

**Comment by sekka1** [comment]
Ok...will take a look at this @max-rocket-internet

**Comment by sekka1** [comment]
@max-rocket-internet I kinda lost track of what is needed here.  What is wrong with this still?

**Comment by cyberw** [comment]
I dont think there is anything we need to do here. The chart is at https://github.com/deliveryhero/helm-charts/tree/master/stable/locust

Any updates or issues are tracked in that project.
